# Sodoku Solver

## Puzzle Setup
Enter the original puzzle here. Mark the blank squares as zeros.

In [1]:
puzzle =  [[5,3,0,0,7,0,0,0,0],
            [6,0,0,1,9,5,0,0,0],
            [0,9,8,0,0,0,0,6,0],
            [8,0,0,0,6,0,0,0,3],
            [4,0,0,8,0,3,0,0,1],
            [7,0,0,0,2,0,0,0,6],
            [0,6,0,0,0,0,2,8,0],
            [0,0,0,4,1,9,0,0,5],
            [0,0,0,0,8,0,0,7,9]] 
solved = False

## Imports

In [2]:
import numpy as np

## Helper Functions

In [3]:
def IsPossible(y,x,n):
    global puzzle
    # check row for number already in row
    for i in range(9):
        if puzzle[y][i] == n:
            return False
    # check for number already in column
    for i in range(9):
        if puzzle[i][x] == n:
            return False
    # there are 3x3 local groups, figure local group coordinates for x,y
    localGroupXOffset = (x//3)*3
    localGroupYOffset = (y//3)*3
    # check the 9 squares in the local grid for number already there
    for i in range(3):
        for j in range(3):
            if puzzle[localGroupYOffset + i][localGroupXOffset + j] == n:
                return False
    # number is possible
    return True

def puzzleHasBlanks():
    for i in range(9):
        for j in range(9):
            if puzzle[i][j] == 0:
                return True
    return False

## Recursive Solve Method

In [4]:
def solve():
    global puzzle, solved
    for y in range(9):
       for x in range(9):
            # find next empty square
            if puzzle[y][x] == 0:
                # try each number 1 to 9
                for n in range(1,10):
                    if IsPossible(y,x,n):
                        # try that number and see how it goes
                        puzzle[y][x] = n
                        solve()
                        if solved:
                            return
                        else:
                            # possible solution didn't work out, backtrack
                            puzzle[y][x] = 0
                return
    # all done  
    solved = True
    print('The solution is:')
    print(np.matrix(puzzle)) 

## Solve the Puzzle

In [5]:
solve()


The solution is:
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
